services:
  mongo:
    image: mongo
    ports:
    - "${MONGO_PORT}:${MONGO_PORT}"
    container_name: mongo
  django:
    image: ghcr.io/denzelhopkins/django:latest
    ports:
    - "${DJANGO_PORT}:${DJANGO_PORT}"
    container_name: django
  vue:
    image: ghcr.io/denzelhopkins/vue:latest
    ports:
    - "${VUE_PORT}:${VUE_PORT}"
    container_name: vue
  kotlin:
    image: ghcr.io/denzelhopkins/kotlin:latest
    environment:
      - spring.data.mongodb.host=mongo
      - spring.data.mongodb.port=${MONGO_PORT}
      - spring.data.mongodb.database=mongo
      - server.port=${KOTLIN_PORT}
    ports:
    - "${KOTLIN_PORT}:${KOTLIN_PORT}"
    container_name: kotlin