services:
  database:
    image: mongo
    ports:
    - "27017:27017"
    container_name: mongo
  django:
    image: ghcr.io/denzelhopkins/django:latest
    ports:
    - "8000:8000"
    container_name: django
  vue:
    image: ghcr.io/denzelhopkins/vue:latest
    container_name: vue
  kotlin:
    image: ghcr.io/denzelhopkins/kotlin:latest
    environment:
      - spring.data.mongodb.host=mongo
      - spring.data.mongodb.port=27017
      - spring.data.mongodb.database=mongo
      - server.port=1000
    ports:
    - "1000:1000"
    container_name: kotlin